<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AdminTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // DB::table('admin')->updateOrInsert([
        $actions = [
            [
                'action_name' => 'Send Email',
                'values' => json_encode([
                    [
                        'columnname' => 'from_name',
                        'fieldname' => 'from_name',
                        'fieldlabel' => 'From Name',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~O',
                        'uitype' => 1,
                        'options' => null, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'from_email',
                        'fieldname' => 'from_email',
                        'fieldlabel' => 'From Email',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~O',
                        'uitype' => 1,
                        'options' => null, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'subject',
                        'fieldname' => 'subject',
                        'fieldlabel' => 'Subject',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 2,
                        'options' => null, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'message',
                        'fieldname' => 'message',
                        'fieldlabel' => 'Message',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~O',
                        'uitype' => 1,
                        'options' => null,
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'atachments',
                        'fieldname' => 'attachments',
                        'fieldlabel' => 'Attachments',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~O',
                        'uitype' => 69,
                        'options' => null, 
                        'info_type' => 'ADV',
                    ],
                ]),
            ],
            [
                'action_name' => 'Send SMS',
                'values' => json_encode([
                    [
                        'columnname' => 'message',
                        'fieldname' => 'message',
                        'fieldlabel' => 'Message',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~O',
                        'uitype' => 1,
                        'options' => null, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'atachments',
                        'fieldname' => 'attachments',
                        'fieldlabel' => 'Attachments',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~O',
                        'uitype' => 69,
                        'options' => null, 
                        'info_type' => 'ADV',
                    ],
                ]),
            ],
            [
                'action_name' => 'Whatsapp',
                'values' => json_encode([
                    [
                        'columnname' => 'message',
                        'fieldname' => 'message',
                        'fieldlabel' => 'Message',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~O',
                        'uitype' => 1,
                        'options' => null, 
                        'info_type' => 'BAS',
                    ],
                ]),
            ],
            [
                'action_name' => 'Create Opportunity',
                'values' => json_encode([
                    [
                        'columnname' => 'select_pipeline',
                        'fieldname' => 'select_pipeline',
                        'fieldlabel' => 'Select Pipeline',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~O',
                        'uitype' => 16,
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'select_stage',
                        'fieldname' => 'select_stage',
                        'fieldlabel' => 'Select Stage',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~O',
                        'uitype' => 16,
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'opportunity_name',
                        'fieldname' => 'opportunity_name',
                        'fieldlabel' => 'Opportunity Name',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~O',
                        'uitype' => 1,
                        'options' => null, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'opportunity_source',
                        'fieldname' => 'opportunity_source',
                        'fieldlabel' => 'Opportunity source',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~O',
                        'uitype' => 1,
                        'options' => null, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'lead_value',
                        'fieldname' => 'lead_value',
                        'fieldlabel' => 'Lead Value',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~O',
                        'uitype' => 1,
                        'options' => null, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'opportunity_status',
                        'fieldname' => 'opportunity_status',
                        'fieldlabel' => 'Opportunity Status',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~O',
                        'uitype' => 16, 
                        'info_type' => 'BAS',
                    ],
                ]),
            ],  
            [
                'action_name' => 'Remove Opportunity',
                'values' => json_encode([
                    [
                        'columnname' => 'select_pipeline',
                        'fieldname' => 'select_pipeline',
                        'fieldlabel' => 'Select Pipeline',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~O',
                        'uitype' => 16,
                        'info_type' => 'BAS',
                    ],
                ]),
            ], 
            [
                'action_name' => 'Send Invoice',
                'values' => json_encode([
                    [
                        'columnname' => 'from_user',
                        'fieldname' => 'from_user',
                        'fieldlabel' => 'From User',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~O',
                        'uitype' => 16,
                        'options' => null, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'invoice_template',
                        'fieldname' => 'invoice_template',
                        'fieldlabel' => 'Invoice Template',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~O',
                        'uitype' => 16,
                        'options' => null, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'payment_mode',
                        'fieldname' => 'payment_mode',
                        'fieldlabel' => 'Payment Mode',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~O',
                        'uitype' => 56,
                        'info_type' => 'BAS',
                    ],
                ]),
            ], 
            [
                'action_name' => 'Add To Workflow',
                'values' => json_encode([
                    [
                        'columnname' => 'workflow_id',
                        'fieldname' => 'workflow_id',
                        'fieldlabel' => 'Workflow Id',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~O',
                        'uitype' => 16, 
                        'info_type' => 'BAS',
                    ],
                ]),
            ],
            [
                'action_name' => 'Remove From Workflow',
                'values' => json_encode([
                    [
                        'columnname' => 'workflow_id',
                        'fieldname' => 'workflow_id',
                        'fieldlabel' => 'Workflow Id',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~O',
                        'uitype' => 16,
                        'info_type' => 'BAS',
                    ],
                ]),
            ], 
            [
                'action_name' => 'Find Contact',
                'values' => json_encode([
                    [
                        'columnname' => 'fields',
                        'fieldname' => 'fields',
                        'fieldlabel' => 'Fields',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 8, 
                        'info_type' => 'BAS',
                    ],
                ]),
            ],
            [
                'action_name' => 'Add Contact Tag',
                'values' => json_encode([
                    [
                        'columnname' => 'tags',
                        'fieldname' => 'tags',
                        'fieldlabel' => 'Tags',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~O',
                        'uitype' => 33, 
                        'info_type' => 'BAS',
                    ],
                ]),
            ],
            [
                'action_name' => 'Remove Contact Tag',
                'values' => json_encode([
                    [
                        'columnname' => 'tags',
                        'fieldname' => 'tags',
                        'fieldlabel' => 'Tags',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~O',
                        'uitype' => 33, 
                        'info_type' => 'BAS',
                    ],
                ]),
            ],
            [
                'action_name' => 'Create Contact',
                'values' => json_encode([
                    [
                        'columnname' => 'fields',
                        'fieldname' => 'fields',
                        'fieldlabel' => 'Fields',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 8, 
                        'info_type' => 'BAS',
                    ],
                ]),
            ],
            [
                'action_name' => 'Update Contact Field',
                'values' => json_encode([
                    [
                        'columnname' => 'fields',
                        'fieldname' => 'fields',
                        'fieldlabel' => 'Fields',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 8, 
                        'info_type' => 'BAS',
                    ],
                ]),
            ],
            [
                'action_name' => 'Delete Contact',
                'values' => null,
            ],
            [
                'action_name' => 'Assign User',
                'values' => json_encode([
                    [
                        'columnname' => 'users',
                        'fieldname' => 'users',
                        'fieldlabel' => 'Users',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 33, 
                        'info_type' => 'BAS',
                    ],
                ]),
            ],
            [
                'action_name' => 'Remove Assigned User',
                'values' => null,
            ],
            [
                'action_name' => 'Go To',
                'values' => null,
            ],
            [
                'action_name' => 'Split',
                'values' => json_encode([
                    [
                        'columnname' => 'distribution_type',
                        'fieldname' => 'distribution_type',
                        'fieldlabel' => 'Distribution Type',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~O',
                        'uitype' => 16, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'paths',
                        'fieldname' => 'paths',
                        'fieldlabel' => 'Paths',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~O',
                        'uitype' => 1, 
                        'info_type' => 'BAS',
                    ],
                ]),
            ],
            [
                'action_name' => 'Drip',
                'values' => json_encode([
                    [
                        'columnname' => 'batch_size',
                        'fieldname' => 'batch_size',
                        'fieldlabel' => 'Batch Size',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 2, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'drip_interval',
                        'fieldname' => 'drip_interval',
                        'fieldlabel' => 'Drip Interval',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 2, 
                        'info_type' => 'BAS',
                    ],
                ]),
            ],
            [
                'action_name' => 'Add Task',
                'values' => json_encode([
                    [
                        'columnname' => 'title',
                        'fieldname' => 'title',
                        'fieldlabel' => 'Title',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 2, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'description',
                        'fieldname' => 'description',
                        'fieldlabel' => 'Description',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~O',
                        'uitype' => 19, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'assign_to',
                        'fieldname' => 'assign_to',
                        'fieldlabel' => 'Assign To',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 16, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'due_in',
                        'fieldname' => 'due_in',
                        'fieldlabel' => 'Due In',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 16, 
                        'info_type' => 'BAS',
                    ],
                ]),
            ],
            [
                'action_name' => 'Update Custom Value',
                'values' => json_encode([
                    [
                        'columnname' => 'custom_value',
                        'fieldname' => 'custom_value',
                        'fieldlabel' => 'Custom Value',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 16, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'current_value',
                        'fieldname' => 'current_value',
                        'fieldlabel' => 'Current Value',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~O',
                        'uitype' => 1, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'new_value',
                        'fieldname' => 'new_value',
                        'fieldlabel' => 'New Value',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 2, 
                        'info_type' => 'BAS',
                    ],
                ]),
            ],
            [
                'action_name' => 'Number Formatter',
                'values' => json_encode([
                    [
                        'columnname' => 'action_type',
                        'fieldname' => 'action_type',
                        'fieldlabel' => 'Action Type',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 16, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'field',
                        'fieldname' => 'field',
                        'fieldlabel' => 'Field',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 16, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'decimal_mark',
                        'fieldname' => 'decimal_mark',
                        'fieldlabel' => 'Decimal Mark',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 16, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'to_format',
                        'fieldname' => 'to_format',
                        'fieldlabel' => 'To format',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 16, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'country_code',
                        'fieldname' => 'country_code',
                        'fieldlabel' => 'Country Code',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 16, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'currency',
                        'fieldname' => 'currency',
                        'fieldlabel' => 'Currency',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 16, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'currency_locale',
                        'fieldname' => 'currency_locale',
                        'fieldlabel' => 'Currency Locale',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 16, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'lower_range',
                        'fieldname' => 'lower_range',
                        'fieldlabel' => 'Lower Range',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 2, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'upper_range',
                        'fieldname' => 'upper_range',
                        'fieldlabel' => 'Upper Range',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 2, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'decimal_points',
                        'fieldname' => 'decimal_points',
                        'fieldlabel' => 'Decimal Points',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~O',
                        'uitype' => 1, 
                        'info_type' => 'BAS',
                    ],
                ]),
            ],
            [
                'action_name' => 'Math Operation',
                'values' => json_encode([
                    [
                        'columnname' => 'field',
                        'fieldname' => 'field',
                        'fieldlabel' => 'Field',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 16, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'operator',
                        'fieldname' => 'operator',
                        'fieldlabel' => 'Operator',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 16, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'days',
                        'fieldname' => 'days',
                        'fieldlabel' => 'Days',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 2, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'months',
                        'fieldname' => 'months',
                        'fieldlabel' => 'Months',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 2, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'years',
                        'fieldname' => 'years',
                        'fieldlabel' => 'Years',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 2, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'update_field',
                        'fieldname' => 'update_field',
                        'fieldlabel' => 'Update Field',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 16, 
                        'info_type' => 'BAS',
                    ],
                ]),
            ],
            [
                'action_name' => 'Date/Time Formatter',
                'values' => json_encode([
                    [
                        'columnname' => 'type',
                        'fieldname' => 'type',
                        'fieldlabel' => 'Type',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 16, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'field',
                        'fieldname' => 'field',
                        'fieldlabel' => 'Field',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 16, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'from_format',
                        'fieldname' => 'from_format',
                        'fieldlabel' => 'From Format',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 16, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'to_format',
                        'fieldname' => 'to_format',
                        'fieldlabel' => 'To Format',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 16, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'start_date',
                        'fieldname' => 'start_date',
                        'fieldlabel' => 'Start Date',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 16, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'start_date_format',
                        'fieldname' => 'start_date_format',
                        'fieldlabel' => 'Start Date Format',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 16, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'end_date',
                        'fieldname' => 'end_date',
                        'fieldlabel' => 'End Date',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 16, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'end_date_format',
                        'fieldname' => 'end_date_format',
                        'fieldlabel' => 'End Date Format',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 16, 
                        'info_type' => 'BAS',
                    ],
                ]),
            ],
            [
                'action_name' => 'Set Event Start Date',
                'values' => json_encode([
                    [
                        'columnname' => 'types',
                        'fieldname' => 'types',
                        'fieldlabel' => 'Type',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 16, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'field',
                        'fieldname' => 'field',
                        'fieldlabel' => 'Field',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~O',
                        'uitype' => 1, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'select_date',
                        'fieldname' => 'select_date',
                        'fieldlabel' => 'Select Date',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~O',
                        'uitype' => 6, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'day_type',
                        'fieldname' => 'day_type',
                        'fieldlabel' => 'Day Type',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 16, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'day_value',
                        'fieldname' => 'day_value',
                        'fieldlabel' => 'Day Value',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 16, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'time',
                        'fieldname' => 'time',
                        'fieldlabel' => 'Time',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 16, 
                        'info_type' => 'BAS',
                    ],
                ]),
            ],
            [
                'action_name' => 'Goal Event',
                'values' => json_encode([
                    [
                        'columnname' => 'Types',
                        'fieldname' => 'Types',
                        'fieldlabel' => 'Type',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 16, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'select_email_event',
                        'fieldname' => 'select_email_event',
                        'fieldlabel' => 'Select Email Event',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 16, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'outcome',
                        'fieldname' => 'outcome',
                        'fieldlabel' => 'Outcome',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 16, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'select',
                        'fieldname' => 'select',
                        'fieldlabel' => 'Select',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 16, 
                        'info_type' => 'BAS',
                    ],
                ]),
            ],
            [
                'action_name' => 'Wait',
                'values' => json_encode([
                    [
                        'columnname' => 'wait_for',
                        'fieldname' => 'wait_for',
                        'fieldlabel' => 'Wait For',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 16, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'wait',
                        'fieldname' => 'wait',
                        'fieldlabel' => 'Wait',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 2, 
                        'info_type' => 'BAS',
                    ],
                ]),
            ],
            [
                'action_name' => 'Text Formatter',
                'values' => json_encode([
                    [
                        'columnname' => 'Type',
                        'fieldname' => 'Type',
                        'fieldlabel' => 'Type',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~M',
                        'uitype' => 16, 
                        'info_type' => 'BAS',
                    ],
                    [
                        'columnname' => 'field',
                        'fieldname' => 'field',
                        'fieldlabel' => 'Field',
                        'generatedtype' => 1,
                        'readonly'  => 1,
                        'presence' => 2,
                        'typeofdata' => 'V~O',
                        'uitype' => 16, 
                        'info_type' => 'BAS',
                    ],
                ]),
            ],
        ];
        foreach ($actions as $action) {
            DB::table('admin')->updateOrInsert(
                ['action_name' => $action['action_name']], // Condition
                ['values' => $action['values'] ?? json_encode([])] // Use default value if null
            );
        }        
    }
}
